name: Deploy Extension (COML)

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./editors/vscode/

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"
                  cache-dependency-path: ./editors/vscode/package-lock.json

            - name: Install
              run: npm install

            - name: Package (.vsix)
              run: npx @vscode/vsce package --allow-missing-repository

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                tag_name: v${{ github.event.inputs.version }}
                files: editors/vscode/*.vsix
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}