name: Publish Extension To Marketplace [VSCODE]

on:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  RUSTFLAGS: "-D warnings -W unreachable-pub"
  RUSTUP_MAX_RETRIES: 10
  FETCH_DEPTH: 0

jobs:
  dist:
    if: ${{ github.repository == 'coml-lang/coml-extension' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: windows-latest
            target: i686-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            code-target: win32-arm64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            container: quay.io/pypa/manylinux_2_28_x86_64
            code-target: linux-x64

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    env:
      RA_TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Rustup
        if: ${{ matrix.container }}
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install Rust Toolchain
        run: |
          rustup update --no-self-update stable
          rustup component add rust-src ${{ 'llvm-tools' || '' }}
          rustup target add ${{ matrix.target }}

      - run: npm ci
        working-directory: editors/vscode

      - name: Build Rust LSP
        run: cargo build --release --targe ${{ matrix.target }} -p coml-lsp
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
          

      - name: Package Extension (Release)
        if: ${{ (github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/release') && matrix.code-target }}
        working-directory: ./editors/vscode/
        run: npx @vscode/vsce package -o "../../dist/coml-extension-${{ matrix.code-target }}.vsix" --target ${{ matrix.code-target }}
