name: Publish Extension To Marketplace [VSCODE]

on:
  workflow_dispatch:

jobs:
  dist:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            code-target: win32-x64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
            # On retire le container temporairement pour débugger plus facilement
            # car il peut causer des problèmes de permissions sur le dossier dist

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      # 1. Compilation du LSP Rust
      - name: Build Rust LSP
        run: cargo build --release --target ${{ matrix.target }} -p coml-lsp

      # 2. Installation des dépendances Node
      - name: Install Node Dependencies
        working-directory: ./editors/vscode
        run: npm install # Utilise install au lieu de ci si ton lockfile n'est pas à jour

      # 3. Préparation des fichiers pour le VSIX
      - name: Prepare Assets
        run: |
          mkdir -p editors/vscode/bin
          mkdir -p dist
          # Copie le binaire compilé dans le dossier de l'extension
          cp target/${{ matrix.target }}/release/coml-lsp* editors/vscode/bin/

      # 4. Packaging
      - name: Package Extension
        working-directory: ./editors/vscode
        run: npx @vscode/vsce package -o "../../dist/coml-extension-${{ matrix.code-target }}.vsix" --target ${{ matrix.code-target }} --no-dependencies

      # 5. Upload l'artéfact pour que TU puisses le télécharger
      - name: Upload VSIX
        uses: actions/upload-artifact@v4
        with:
          name: coml-extension-${{ matrix.code-target }}
          path: dist/*.vsix
